// <auto-generated>
//   Generated by flatc manually for PanelNester project persistence.
// </auto-generated>
#nullable enable
using Google.FlatBuffers;

namespace PanelNester.Services.Persistence.FlatBuffers;

public struct ProjectDocument : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public static ProjectDocument GetRootAsProjectDocument(ByteBuffer _bb) => GetRootAsProjectDocument(_bb, new ProjectDocument());
    public static ProjectDocument GetRootAsProjectDocument(ByteBuffer _bb, ProjectDocument obj)
    {
        _bb.Position = _bb.GetInt(_bb.Position) + _bb.Position;
        return obj.__assign(_bb.Position, _bb);
    }

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public ProjectDocument __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public int Version
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public string? ProjectId
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public ProjectMetadata? Metadata
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? new ProjectMetadata().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public ProjectSettings? Settings
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? new ProjectSettings().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public Material? MaterialSnapshots(int j)
    {
        var o = __p.__offset(12);
        return o != 0 ? new Material().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int MaterialSnapshotsLength
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public ProjectState? State
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? new ProjectState().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public static void StartProjectDocument(FlatBufferBuilder builder) => builder.StartTable(6);
    public static void AddVersion(FlatBufferBuilder builder, int version) => builder.AddInt(0, version, 0);
    public static void AddProjectId(FlatBufferBuilder builder, StringOffset projectIdOffset) => builder.AddOffset(1, projectIdOffset.Value, 0);
    public static void AddMetadata(FlatBufferBuilder builder, Offset<ProjectMetadata> metadataOffset) => builder.AddOffset(2, metadataOffset.Value, 0);
    public static void AddSettings(FlatBufferBuilder builder, Offset<ProjectSettings> settingsOffset) => builder.AddOffset(3, settingsOffset.Value, 0);
    public static void AddMaterialSnapshots(FlatBufferBuilder builder, VectorOffset materialSnapshotsOffset) => builder.AddOffset(4, materialSnapshotsOffset.Value, 0);
    public static void AddState(FlatBufferBuilder builder, Offset<ProjectState> stateOffset) => builder.AddOffset(5, stateOffset.Value, 0);

    public static VectorOffset CreateMaterialSnapshotsVector(FlatBufferBuilder builder, Offset<Material>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static Offset<ProjectDocument> EndProjectDocument(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<ProjectDocument>(o);
    }

    public static void FinishProjectDocumentBuffer(FlatBufferBuilder builder, Offset<ProjectDocument> offset) =>
        builder.Finish(offset.Value);
}

public struct ProjectMetadata : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public ProjectMetadata __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? ProjectName
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ProjectNumber
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? CustomerName
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Estimator
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Drafter
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Pm
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public long DateTicks
    {
        get
        {
            var o = __p.__offset(16);
            return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : 0;
        }
    }

    public bool HasDate
    {
        get
        {
            var o = __p.__offset(18);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public string? Revision
    {
        get
        {
            var o = __p.__offset(20);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Notes
    {
        get
        {
            var o = __p.__offset(22);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public static void StartProjectMetadata(FlatBufferBuilder builder) => builder.StartTable(10);
    public static void AddProjectName(FlatBufferBuilder builder, StringOffset projectNameOffset) => builder.AddOffset(0, projectNameOffset.Value, 0);
    public static void AddProjectNumber(FlatBufferBuilder builder, StringOffset projectNumberOffset) => builder.AddOffset(1, projectNumberOffset.Value, 0);
    public static void AddCustomerName(FlatBufferBuilder builder, StringOffset customerNameOffset) => builder.AddOffset(2, customerNameOffset.Value, 0);
    public static void AddEstimator(FlatBufferBuilder builder, StringOffset estimatorOffset) => builder.AddOffset(3, estimatorOffset.Value, 0);
    public static void AddDrafter(FlatBufferBuilder builder, StringOffset drafterOffset) => builder.AddOffset(4, drafterOffset.Value, 0);
    public static void AddPm(FlatBufferBuilder builder, StringOffset pmOffset) => builder.AddOffset(5, pmOffset.Value, 0);
    public static void AddDateTicks(FlatBufferBuilder builder, long dateTicks) => builder.AddLong(6, dateTicks, 0);
    public static void AddHasDate(FlatBufferBuilder builder, bool hasDate) => builder.AddBool(7, hasDate, false);
    public static void AddRevision(FlatBufferBuilder builder, StringOffset revisionOffset) => builder.AddOffset(8, revisionOffset.Value, 0);
    public static void AddNotes(FlatBufferBuilder builder, StringOffset notesOffset) => builder.AddOffset(9, notesOffset.Value, 0);

    public static Offset<ProjectMetadata> EndProjectMetadata(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<ProjectMetadata>(o);
    }
}

public struct ProjectSettings : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public ProjectSettings __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public double KerfWidth
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public ReportSettings? ReportSettings
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? new ReportSettings().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public static void StartProjectSettings(FlatBufferBuilder builder) => builder.StartTable(2);
    public static void AddKerfWidth(FlatBufferBuilder builder, double kerfWidth) => builder.AddDouble(0, kerfWidth, 0);
    public static void AddReportSettings(FlatBufferBuilder builder, Offset<ReportSettings> reportSettingsOffset) => builder.AddOffset(1, reportSettingsOffset.Value, 0);

    public static Offset<ProjectSettings> EndProjectSettings(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<ProjectSettings>(o);
    }
}

public struct ReportSettings : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public ReportSettings __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? CompanyName
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ReportTitle
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ProjectJobName
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ProjectJobNumber
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public long ReportDateTicks
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : 0;
        }
    }

    public bool HasReportDate
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public string? Notes
    {
        get
        {
            var o = __p.__offset(16);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public static void StartReportSettings(FlatBufferBuilder builder) => builder.StartTable(7);
    public static void AddCompanyName(FlatBufferBuilder builder, StringOffset companyNameOffset) => builder.AddOffset(0, companyNameOffset.Value, 0);
    public static void AddReportTitle(FlatBufferBuilder builder, StringOffset reportTitleOffset) => builder.AddOffset(1, reportTitleOffset.Value, 0);
    public static void AddProjectJobName(FlatBufferBuilder builder, StringOffset projectJobNameOffset) => builder.AddOffset(2, projectJobNameOffset.Value, 0);
    public static void AddProjectJobNumber(FlatBufferBuilder builder, StringOffset projectJobNumberOffset) => builder.AddOffset(3, projectJobNumberOffset.Value, 0);
    public static void AddReportDateTicks(FlatBufferBuilder builder, long reportDateTicks) => builder.AddLong(4, reportDateTicks, 0);
    public static void AddHasReportDate(FlatBufferBuilder builder, bool hasReportDate) => builder.AddBool(5, hasReportDate, false);
    public static void AddNotes(FlatBufferBuilder builder, StringOffset notesOffset) => builder.AddOffset(6, notesOffset.Value, 0);

    public static Offset<ReportSettings> EndReportSettings(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<ReportSettings>(o);
    }
}

public struct Material : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public Material __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? MaterialId
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Name
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double SheetLength
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double SheetWidth
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public bool AllowRotation
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public double DefaultSpacing
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double DefaultEdgeMargin
    {
        get
        {
            var o = __p.__offset(16);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public string? ColorFinish
    {
        get
        {
            var o = __p.__offset(18);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? Notes
    {
        get
        {
            var o = __p.__offset(20);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double CostPerSheet
    {
        get
        {
            var o = __p.__offset(22);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public bool HasCostPerSheet
    {
        get
        {
            var o = __p.__offset(24);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public static void StartMaterial(FlatBufferBuilder builder) => builder.StartTable(11);
    public static void AddMaterialId(FlatBufferBuilder builder, StringOffset materialIdOffset) => builder.AddOffset(0, materialIdOffset.Value, 0);
    public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) => builder.AddOffset(1, nameOffset.Value, 0);
    public static void AddSheetLength(FlatBufferBuilder builder, double sheetLength) => builder.AddDouble(2, sheetLength, 0);
    public static void AddSheetWidth(FlatBufferBuilder builder, double sheetWidth) => builder.AddDouble(3, sheetWidth, 0);
    public static void AddAllowRotation(FlatBufferBuilder builder, bool allowRotation) => builder.AddBool(4, allowRotation, false);
    public static void AddDefaultSpacing(FlatBufferBuilder builder, double defaultSpacing) => builder.AddDouble(5, defaultSpacing, 0);
    public static void AddDefaultEdgeMargin(FlatBufferBuilder builder, double defaultEdgeMargin) => builder.AddDouble(6, defaultEdgeMargin, 0);
    public static void AddColorFinish(FlatBufferBuilder builder, StringOffset colorFinishOffset) => builder.AddOffset(7, colorFinishOffset.Value, 0);
    public static void AddNotes(FlatBufferBuilder builder, StringOffset notesOffset) => builder.AddOffset(8, notesOffset.Value, 0);
    public static void AddCostPerSheet(FlatBufferBuilder builder, double costPerSheet) => builder.AddDouble(9, costPerSheet, 0);
    public static void AddHasCostPerSheet(FlatBufferBuilder builder, bool hasCostPerSheet) => builder.AddBool(10, hasCostPerSheet, false);

    public static Offset<Material> EndMaterial(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<Material>(o);
    }
}

public struct ProjectState : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public ProjectState __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? SourceFilePath
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public PartRow? Parts(int j)
    {
        var o = __p.__offset(6);
        return o != 0 ? new PartRow().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int PartsLength
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public string? SelectedMaterialId
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public NestResponse? LastNestingResult
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? new NestResponse().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public BatchNestResponse? LastBatchNestingResult
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? new BatchNestResponse().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public static void StartProjectState(FlatBufferBuilder builder) => builder.StartTable(5);
    public static void AddSourceFilePath(FlatBufferBuilder builder, StringOffset sourceFilePathOffset) => builder.AddOffset(0, sourceFilePathOffset.Value, 0);
    public static void AddParts(FlatBufferBuilder builder, VectorOffset partsOffset) => builder.AddOffset(1, partsOffset.Value, 0);
    public static void AddSelectedMaterialId(FlatBufferBuilder builder, StringOffset selectedMaterialIdOffset) => builder.AddOffset(2, selectedMaterialIdOffset.Value, 0);
    public static void AddLastNestingResult(FlatBufferBuilder builder, Offset<NestResponse> lastNestingResultOffset) => builder.AddOffset(3, lastNestingResultOffset.Value, 0);
    public static void AddLastBatchNestingResult(FlatBufferBuilder builder, Offset<BatchNestResponse> lastBatchNestingResultOffset) =>
        builder.AddOffset(4, lastBatchNestingResultOffset.Value, 0);

    public static VectorOffset CreatePartsVector(FlatBufferBuilder builder, Offset<PartRow>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static Offset<ProjectState> EndProjectState(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<ProjectState>(o);
    }
}

public struct PartRow : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public PartRow __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? RowId
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ImportedId
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? LengthText
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double Length
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public string? WidthText
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double Width
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public string? QuantityText
    {
        get
        {
            var o = __p.__offset(16);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public int Quantity
    {
        get
        {
            var o = __p.__offset(18);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public string? MaterialName
    {
        get
        {
            var o = __p.__offset(20);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ValidationStatus
    {
        get
        {
            var o = __p.__offset(22);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ValidationMessages(int j)
    {
        var o = __p.__offset(24);
        return o != 0 ? __p.__string(__p.__vector(o) + (j * 4)) : null;
    }

    public int ValidationMessagesLength
    {
        get
        {
            var o = __p.__offset(24);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public string? Group
    {
        get
        {
            var o = __p.__offset(26);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public static void StartPartRow(FlatBufferBuilder builder) => builder.StartTable(12);
    public static void AddRowId(FlatBufferBuilder builder, StringOffset rowIdOffset) => builder.AddOffset(0, rowIdOffset.Value, 0);
    public static void AddImportedId(FlatBufferBuilder builder, StringOffset importedIdOffset) => builder.AddOffset(1, importedIdOffset.Value, 0);
    public static void AddLengthText(FlatBufferBuilder builder, StringOffset lengthTextOffset) => builder.AddOffset(2, lengthTextOffset.Value, 0);
    public static void AddLength(FlatBufferBuilder builder, double length) => builder.AddDouble(3, length, 0);
    public static void AddWidthText(FlatBufferBuilder builder, StringOffset widthTextOffset) => builder.AddOffset(4, widthTextOffset.Value, 0);
    public static void AddWidth(FlatBufferBuilder builder, double width) => builder.AddDouble(5, width, 0);
    public static void AddQuantityText(FlatBufferBuilder builder, StringOffset quantityTextOffset) => builder.AddOffset(6, quantityTextOffset.Value, 0);
    public static void AddQuantity(FlatBufferBuilder builder, int quantity) => builder.AddInt(7, quantity, 0);
    public static void AddMaterialName(FlatBufferBuilder builder, StringOffset materialNameOffset) => builder.AddOffset(8, materialNameOffset.Value, 0);
    public static void AddValidationStatus(FlatBufferBuilder builder, StringOffset validationStatusOffset) => builder.AddOffset(9, validationStatusOffset.Value, 0);
    public static void AddValidationMessages(FlatBufferBuilder builder, VectorOffset validationMessagesOffset) => builder.AddOffset(10, validationMessagesOffset.Value, 0);
    public static void AddGroup(FlatBufferBuilder builder, StringOffset groupOffset) => builder.AddOffset(11, groupOffset.Value, 0);

    public static VectorOffset CreateValidationMessagesVector(FlatBufferBuilder builder, StringOffset[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static Offset<PartRow> EndPartRow(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<PartRow>(o);
    }
}

public struct NestResponse : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public NestResponse __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public bool Success
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public NestSheet? Sheets(int j)
    {
        var o = __p.__offset(6);
        return o != 0 ? new NestSheet().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int SheetsLength
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public NestPlacement? Placements(int j)
    {
        var o = __p.__offset(8);
        return o != 0 ? new NestPlacement().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int PlacementsLength
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public UnplacedItem? UnplacedItems(int j)
    {
        var o = __p.__offset(10);
        return o != 0 ? new UnplacedItem().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int UnplacedItemsLength
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public MaterialSummary? Summary
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? new MaterialSummary().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public static void StartNestResponse(FlatBufferBuilder builder) => builder.StartTable(5);
    public static void AddSuccess(FlatBufferBuilder builder, bool success) => builder.AddBool(0, success, false);
    public static void AddSheets(FlatBufferBuilder builder, VectorOffset sheetsOffset) => builder.AddOffset(1, sheetsOffset.Value, 0);
    public static void AddPlacements(FlatBufferBuilder builder, VectorOffset placementsOffset) => builder.AddOffset(2, placementsOffset.Value, 0);
    public static void AddUnplacedItems(FlatBufferBuilder builder, VectorOffset unplacedItemsOffset) => builder.AddOffset(3, unplacedItemsOffset.Value, 0);
    public static void AddSummary(FlatBufferBuilder builder, Offset<MaterialSummary> summaryOffset) => builder.AddOffset(4, summaryOffset.Value, 0);

    public static VectorOffset CreateSheetsVector(FlatBufferBuilder builder, Offset<NestSheet>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static VectorOffset CreatePlacementsVector(FlatBufferBuilder builder, Offset<NestPlacement>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static VectorOffset CreateUnplacedItemsVector(FlatBufferBuilder builder, Offset<UnplacedItem>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static Offset<NestResponse> EndNestResponse(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<NestResponse>(o);
    }
}

public struct NestSheet : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public NestSheet __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? SheetId
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public int SheetNumber
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public string? MaterialName
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double SheetLength
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double SheetWidth
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double UtilizationPercent
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public static void StartNestSheet(FlatBufferBuilder builder) => builder.StartTable(6);
    public static void AddSheetId(FlatBufferBuilder builder, StringOffset sheetIdOffset) => builder.AddOffset(0, sheetIdOffset.Value, 0);
    public static void AddSheetNumber(FlatBufferBuilder builder, int sheetNumber) => builder.AddInt(1, sheetNumber, 0);
    public static void AddMaterialName(FlatBufferBuilder builder, StringOffset materialNameOffset) => builder.AddOffset(2, materialNameOffset.Value, 0);
    public static void AddSheetLength(FlatBufferBuilder builder, double sheetLength) => builder.AddDouble(3, sheetLength, 0);
    public static void AddSheetWidth(FlatBufferBuilder builder, double sheetWidth) => builder.AddDouble(4, sheetWidth, 0);
    public static void AddUtilizationPercent(FlatBufferBuilder builder, double utilizationPercent) => builder.AddDouble(5, utilizationPercent, 0);

    public static Offset<NestSheet> EndNestSheet(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<NestSheet>(o);
    }
}

public struct NestPlacement : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public NestPlacement __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? PlacementId
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? SheetId
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? PartId
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public double X
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double Y
    {
        get
        {
            var o = __p.__offset(12);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double Width
    {
        get
        {
            var o = __p.__offset(14);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public double Height
    {
        get
        {
            var o = __p.__offset(16);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public bool Rotated90
    {
        get
        {
            var o = __p.__offset(18);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public string? Group
    {
        get
        {
            var o = __p.__offset(20);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public static void StartNestPlacement(FlatBufferBuilder builder) => builder.StartTable(9);
    public static void AddPlacementId(FlatBufferBuilder builder, StringOffset placementIdOffset) => builder.AddOffset(0, placementIdOffset.Value, 0);
    public static void AddSheetId(FlatBufferBuilder builder, StringOffset sheetIdOffset) => builder.AddOffset(1, sheetIdOffset.Value, 0);
    public static void AddPartId(FlatBufferBuilder builder, StringOffset partIdOffset) => builder.AddOffset(2, partIdOffset.Value, 0);
    public static void AddX(FlatBufferBuilder builder, double x) => builder.AddDouble(3, x, 0);
    public static void AddY(FlatBufferBuilder builder, double y) => builder.AddDouble(4, y, 0);
    public static void AddWidth(FlatBufferBuilder builder, double width) => builder.AddDouble(5, width, 0);
    public static void AddHeight(FlatBufferBuilder builder, double height) => builder.AddDouble(6, height, 0);
    public static void AddRotated90(FlatBufferBuilder builder, bool rotated90) => builder.AddBool(7, rotated90, false);
    public static void AddGroup(FlatBufferBuilder builder, StringOffset groupOffset) => builder.AddOffset(8, groupOffset.Value, 0);

    public static Offset<NestPlacement> EndNestPlacement(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<NestPlacement>(o);
    }
}

public struct UnplacedItem : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public UnplacedItem __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? PartId
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ReasonCode
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? ReasonDescription
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public static void StartUnplacedItem(FlatBufferBuilder builder) => builder.StartTable(3);
    public static void AddPartId(FlatBufferBuilder builder, StringOffset partIdOffset) => builder.AddOffset(0, partIdOffset.Value, 0);
    public static void AddReasonCode(FlatBufferBuilder builder, StringOffset reasonCodeOffset) => builder.AddOffset(1, reasonCodeOffset.Value, 0);
    public static void AddReasonDescription(FlatBufferBuilder builder, StringOffset reasonDescriptionOffset) => builder.AddOffset(2, reasonDescriptionOffset.Value, 0);

    public static Offset<UnplacedItem> EndUnplacedItem(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<UnplacedItem>(o);
    }
}

public struct MaterialSummary : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public MaterialSummary __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public int TotalSheets
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public int TotalPlaced
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public int TotalUnplaced
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : 0;
        }
    }

    public double OverallUtilization
    {
        get
        {
            var o = __p.__offset(10);
            return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : 0;
        }
    }

    public static void StartMaterialSummary(FlatBufferBuilder builder) => builder.StartTable(4);
    public static void AddTotalSheets(FlatBufferBuilder builder, int totalSheets) => builder.AddInt(0, totalSheets, 0);
    public static void AddTotalPlaced(FlatBufferBuilder builder, int totalPlaced) => builder.AddInt(1, totalPlaced, 0);
    public static void AddTotalUnplaced(FlatBufferBuilder builder, int totalUnplaced) => builder.AddInt(2, totalUnplaced, 0);
    public static void AddOverallUtilization(FlatBufferBuilder builder, double overallUtilization) => builder.AddDouble(3, overallUtilization, 0);

    public static Offset<MaterialSummary> EndMaterialSummary(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<MaterialSummary>(o);
    }
}

public struct BatchNestResponse : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public BatchNestResponse __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public bool Success
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 && __p.bb.Get(o + __p.bb_pos) != 0;
        }
    }

    public NestResponse? LegacyResult
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? new NestResponse().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public MaterialNestResult? MaterialResults(int j)
    {
        var o = __p.__offset(8);
        return o != 0 ? new MaterialNestResult().__assign(__p.__indirect(__p.__vector(o) + (j * 4)), __p.bb) : null;
    }

    public int MaterialResultsLength
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? __p.__vector_len(o) : 0;
        }
    }

    public static void StartBatchNestResponse(FlatBufferBuilder builder) => builder.StartTable(3);
    public static void AddSuccess(FlatBufferBuilder builder, bool success) => builder.AddBool(0, success, false);
    public static void AddLegacyResult(FlatBufferBuilder builder, Offset<NestResponse> legacyResultOffset) => builder.AddOffset(1, legacyResultOffset.Value, 0);
    public static void AddMaterialResults(FlatBufferBuilder builder, VectorOffset materialResultsOffset) => builder.AddOffset(2, materialResultsOffset.Value, 0);

    public static VectorOffset CreateMaterialResultsVector(FlatBufferBuilder builder, Offset<MaterialNestResult>[] data)
    {
        builder.StartVector(4, data.Length, 4);
        for (var i = data.Length - 1; i >= 0; i--)
        {
            builder.AddOffset(data[i].Value);
        }

        return builder.EndVector();
    }

    public static Offset<BatchNestResponse> EndBatchNestResponse(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<BatchNestResponse>(o);
    }
}

public struct MaterialNestResult : IFlatbufferObject
{
    private Table __p;
    public ByteBuffer ByteBuffer => __p.bb;

    public void __init(int _i, ByteBuffer _bb) => __p = new Table(_i, _bb);
    public MaterialNestResult __assign(int _i, ByteBuffer _bb)
    {
        __init(_i, _bb);
        return this;
    }

    public string? MaterialName
    {
        get
        {
            var o = __p.__offset(4);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public string? MaterialId
    {
        get
        {
            var o = __p.__offset(6);
            return o != 0 ? __p.__string(o + __p.bb_pos) : null;
        }
    }

    public NestResponse? Result
    {
        get
        {
            var o = __p.__offset(8);
            return o != 0 ? new NestResponse().__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null;
        }
    }

    public static void StartMaterialNestResult(FlatBufferBuilder builder) => builder.StartTable(3);
    public static void AddMaterialName(FlatBufferBuilder builder, StringOffset materialNameOffset) => builder.AddOffset(0, materialNameOffset.Value, 0);
    public static void AddMaterialId(FlatBufferBuilder builder, StringOffset materialIdOffset) => builder.AddOffset(1, materialIdOffset.Value, 0);
    public static void AddResult(FlatBufferBuilder builder, Offset<NestResponse> resultOffset) => builder.AddOffset(2, resultOffset.Value, 0);

    public static Offset<MaterialNestResult> EndMaterialNestResult(FlatBufferBuilder builder)
    {
        var o = builder.EndTable();
        return new Offset<MaterialNestResult>(o);
    }
}
